paths:
  /tasks:
    post:
      summary: Add task to card
      description: Adds a task to an existing task card.
      tags:
        - Tasks
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../../components/schemas/tasks/Task.yaml'
      responses:
        '201':
          description: Task added
          content:
            application/json:
              schema:
                $ref: '../../components/schemas/tasks/Task.yaml'
