paths:
  /tasks/theory:
    post:
      summary: Add theory material to card
      description: Creates or attaches theory content to a task card.
      tags:
        - Tasks
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../../components/schemas/tasks/TheoryMaterial.yaml'
      responses:
        '201':
          description: Theory material created
          content:
            application/json:
              schema:
                $ref: '../../components/schemas/tasks/TheoryMaterial.yaml'
