"""Изменена модель ученика

Revision ID: 1b0251fbe8c7
Revises: aef7ef0441b4
Create Date: 2025-06-06 21:03:43.377454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0251fbe8c7'
down_revision = 'aef7ef0441b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('plain_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plain_password', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
