"""Модель Student изменена. Добавлены новые столбцы: логин, пароль

Revision ID: 45b0676d3b85
Revises: bca92bb8e5ef
Create Date: 2025-06-01 09:20:24.817371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b0676d3b85'
down_revision = 'bca92bb8e5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('letter', sa.String(length=1), nullable=False))
        batch_op.add_column(sa.Column('student_number', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_student_username', ['username'])
        batch_op.drop_column('invitation_sent')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('invitation_sent', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('student_number')
        batch_op.drop_column('letter')
        batch_op.drop_column('grade')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
