"""Изменена строка в модели AssesmentResult в models.py

Revision ID: 55632bc94b2e
Revises: 5a3cee70fb08
Create Date: 2025-06-03 14:03:06.033219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55632bc94b2e'
down_revision = '5a3cee70fb08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
