"""Переименован столбец на created_at

Revision ID: 5a3cee70fb08
Revises: 71a5f8f3b58a
Create Date: 2025-06-02 21:52:05.131737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3cee70fb08'
down_revision = '71a5f8f3b58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
