"""Изменена модель ученика

Revision ID: 66c1c255e653
Revises: 1b0251fbe8c7
Create Date: 2025-06-07 00:23:17.310156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c1c255e653'
down_revision = '1b0251fbe8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plain_password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('plain_password')

    # ### end Alembic commands ###
