"""Add StudentProgress model

Revision ID: 824ed89f18d7
Revises: 55632bc94b2e
Create Date: 2025-06-03 23:12:45.531701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824ed89f18d7'
down_revision = '55632bc94b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('initial_test_completed', sa.Boolean(), nullable=True),
    sa.Column('learning_completed', sa.Boolean(), nullable=True),
    sa.Column('final_test_completed', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_progress')
    # ### end Alembic commands ###
