"""Добавлена роль Ученик

Revision ID: 882335afdc7c
Revises: bb9a3d87f492
Create Date: 2025-06-01 15:53:39.988472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882335afdc7c'
down_revision = 'bb9a3d87f492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='student'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE student SET role = 'student' WHERE role IS NULL")

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('role', nullable=False)

    # ### end Alembic commands ###
