"""Изменены модели для скачивания паролей учителем

Revision ID: 9835cd28b3fb
Revises: 824ed89f18d7
Create Date: 2025-06-06 15:41:06.652550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9835cd28b3fb'
down_revision = '824ed89f18d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plain_password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('plain_password')

    # ### end Alembic commands ###
