"""Add email confirmation fields

Revision ID: bca92bb8e5ef
Revises: b3692f0a4b4f
Create Date: 2025-05-18 16:20:21.213270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca92bb8e5ef'
down_revision = 'b3692f0a4b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('progress_completed')
        batch_op.drop_column('status')
        batch_op.drop_column('progress_total')
        batch_op.drop_column('last_active')
        batch_op.drop_column('invitation_token')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('email_code_created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('invitation_token')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('invitation_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('email_code_created_at')
        batch_op.drop_column('email_code')
        batch_op.drop_column('email_confirmed')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitation_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_active', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('progress_total', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('progress_completed', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
